server:
  port: 8002
security:
  oauth2:
    client:
      client-id: client2
      client-secret: 123
#      获取token地址
      access-token-uri: http://localhost:9000/oauth/token
#      将用户重定向到授权地址
      userAuthorizationUri: http://localhost:9000/oauth/authorize
    resource:
#      token-info-uri:
      #用token获取用户详情的地址
#      user-info-uri: http://localhost:9000/user/me
      jwt:
        #直接配置jwt签名秘钥
        key-value: secret!
      #获取JWT的公钥
#        key-uri: http://127.0.0.1:9000/oauth/token_key
spring:
  thymeleaf:
    cache: false